Repository adhusch/PaCER, pull requests merged in 2019-04, with the labels that each got.

#43 Adding doc template to function invPolyArcLength3
  src/Functions/invPolyArcLength3.m
Labels: documentation, ready to merge, requires changes

#44 Adding doc template to function largestConnCompSliceWise
  src/Functions/largestConnCompSliceWise.m
Labels: documentation, ready to merge, requires changes

#41 Adding doc template to function fitParamPolyToSkeleton
  src/Functions/fitParamPolyToSkeleton.m
Labels: documentation, ready to merge, requires changes

#46 Adding doc template to function polyArcLength3
  src/Functions/polyArcLength3.m
Labels: documentation, ready to merge, requires changes

#40 Adding doc to function extractElectrodePointclouds
  src/Functions/extractElectrodePointclouds.m
Labels: documentation, ready to merge, requires changes

#47 Adding doc template to funtion polyval3
  src/Functions/polyval3.m
Labels: documentation, ready to merge, requires changes

#54 update the url of the main image
  README.rst
Labels: documentation, ready to merge

#51 Test for extractElectrodePointclouds
  .artenolis.yml
  .gitignore
  SETUP_PACER.m
  codecov.yml
  external/rdir/LICENSE.md
  external/rdir/README.md
  external/rdir/enhanced_rdir.m
  external/rdir/rdir.m
  src/Functions/createSimpleMPRWorldCoordinates.m
  test/base/clearGlobal.m
  test/base/getEnvironment.m
  test/base/getFilesInDir.m
  test/base/getGlobalValue.m
  test/base/getIgnoredFiles.m
  test/base/restoreEnvironment.m
  test/base/runScriptFile.m
  test/base/runTestSuite.m
  test/base/setGlobal.m
  test/base/verifyFunctionError.m
  test/suite/testextractElectrodePointclouds.m
  test/testAll.m
Labels: do not merge

#53 Test determineElectrodeType
  test/suite/refData_determineElectrodeType.mat
  test/suite/testDetermineElectrodeType.m
Labels: ready to merge

#56 Auto deploy documentation
  .artenolis.yml
  docs/.documenter.enc
  docs/requirements.txt
Labels: documentation, ready to merge

#42 Adding doc template to getIntensityPeaks function
  src/Functions/getIntensityPeaks.m
Labels: documentation, ready to merge

#45 Adding doc template to function plotIntensityProfileAndPeaks
  src/Functions/plotIntensityProfileAndPeaks.m
Labels: documentation, ready to merge
