Repository adhusch/PaCER, pull requests merged in 2019-03, with the labels that each got.

#27 testAll folder
  .artenolis/runtests.sh
  test/testAll.m
Labels: do not merge, requires changes

#35 Regular merge of develop
  .artenolis/runtests.sh
  src/Functions/LICENSE
  test/testAll.m
Labels: do not merge

#26 Adding documentation to the function determineElectrodeType.
  src/Functions/determineElectrodeType.m
Labels: documentation, ready to merge

#28 Adding documentation template to function createSimpleMPRWorldCoordinates
  src/Functions/createSimpleMPRWorldCoordinates.m
Labels: documentation, ready to merge

#32 Adding documentation template to function extractBrainConvHull
  src/Functions/extractBrainConvHull.m
Labels: documentation, ready to merge

#36 change of name of function orr to oor
  src/Functions/oor.m
Labels: ready to merge

#38 Adding doc.structure folder for document generation
  docs/requirements.txt
  docs/source/conf.py
  docs/source/contents.rst
  docs/source/modules/functions/index.rst
  docs/source/modules/index.rst
Labels: ready to merge

#39 update URLs of documentation dependencies
  docs/requirements.txt
Labels: ready to merge

#49 update of badge url to unprotected
  README.rst
Labels: documentation, ready to merge

#37 Adding the doc template to function oor
  src/Functions/oor.m
Labels: ready to merge

#50 YML commands to update data repo on ARTENOLIS
  .artenolis.yml
Labels: ready to merge

#48 Adding doc template to function refitElec
  src/Functions/refitElec.m
Labels: documentation, ready to merge

#52 verifyFunctionError
  test/verifyFunctionError.m
Labels: ready to merge
